name: neom_commons
description: Commons for Open Neom.
version: 3.0.0
homepage: https://github.com/Open-Neom/neom_commons

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  neom_core: ^3.0.0

  # TRANSITIVE DEPENDENCIES FOR PUB.DEV PUBLISHING
#  sint: ^1.0.0
#  http: ^1.6.0
#  url_launcher: ^6.3.2
#  path: ^1.9.1
#  path_provider: ^2.1.5

  rflutter_alert: ^2.0.7

  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.9.1
  lucide_icons_flutter: ^3.1.8

  intl: ^0.20.2
  readmore: ^3.0.0
  animated_text_kit: ^4.3.0
  get_time_ago: ^2.3.2
  flutter_rating_bar: ^4.0.1
  flutter_linkify: ^6.0.0
  hashtagable_v3: ^3.0.1

  carousel_slider: ^5.1.1
  flutter_slider_indicator: ^1.0.0
  rubber: ^1.1.0

  intl_phone_field: ^3.2.0
  share_plus: ^12.0.1

  crypto: ^3.0.7

  webview_flutter: ^4.13.0
  permission_handler: ^12.0.0+1
  app_links: ^7.0.0
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
